#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>
#include <stdbool.h>

const int SPEC = 99;

/**
Problem 12
==========


     The sequence of triangle numbers is generated by adding the natural
     numbers. So the 7^th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
     28. The first ten terms would be:

                                        1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

     Let us list the factors of the first seven triangle numbers:

            1: 1
            3: 1,3
            6: 1,2,3,6
         10: 1,2,5,10
         15: 1,3,5,15
         21: 1,3,7,21
         28: 1,2,4,7,14,28

     We can see that 28 is the first triangle number to have over five
     divisors.

     What is the value of the first triangle number to have over five hundred
     divisors?


     Answer: 8091de7d285989bbfa9a2f9f3bdcc7c0

*/

int
countFactors(double n)
{
// from "cracking the coding interview" page 98, method for checking primality, slightly optimized to check only sqrt(n)
    int numFactors;
    for(double k = 0; k <= n; k++)
    {
        if (n % k == 0)
        {
            numFactors += 1;
        }
    }
    return numFactors;
}

int main(void){
    double i = 0;
    int numFactors = 0;

    while(numFactors <= 500)
    {
        i++;
        numFactors = countFactors(i);
    }
    printf("The number '%f' is the first triangle number with over %d divisors", i, numFactors);
    return EXIT_SUCCESS;
}
